name: commit-lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: "Commit lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-commit-lint@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          config: .commitlintrc.json
